Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-7747d01e"
    aws.tags = {
      "Name" => "vagrant-test"
    }
    aws.keypair_name = "es1"
    aws.security_groups = ["default"]

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/es1"
  end
end
