#!/bin/sh

system=$(uname -mo)
nix_arch=$system
username=${LOGNAME:-$(whoami)}

if [ "$system" = "arm64 Darwin" -o "$system" = "Darwin arm64" ]; then
  nix_arch=aarch64-darwin
elif [ "$system" = "x86_64 GNU/Linux" ]; then
  nix_arch=x86_64-linux
else
  nix_arch=aarch64-linux
fi

echo BUILDING ${username}@${nix_arch}

(
  cd "$HOME/.config/home-manager" || exit 1
  if [ -z "${KEEP_FLAKE_LOCK:-}" ]; then
    rm -f flake.lock
  fi
  nix_args=""
  if [ -n "${NIXPKGS_INPUT:-}" ]; then
    nix_args="--override-input nixpkgs ${NIXPKGS_INPUT}"
  fi
  nix run github:nix-community/home-manager/release-25.11 -- \
        switch --flake ".#${username}@${nix_arch}" ${nix_args}
)
