#!/bin/sh

system=$(uname -mo)
nix_arch=$system
username=${LOGNAME:-$(whoami)}

if [ "$system" = "arm64 Darwin" -o "$system" = "Darwin arm64" ]; then
  nix_arch=aarch64-darwin
elif [ "$system" = "x86_64 GNU/Linux" ]; then
  nix_arch=x86_64-linux
else
  nix_arch=aarch64-linux
fi

echo BUILDING ${username}@${nix_arch}

(
  cd "$HOME/.config/home-manager" || exit 1

  if [ "${UPDATE:-}" = "1" ]; then
    echo "Updating flake dependencies..."
    nix flake update
  fi

  nix_args=""
  if [ -n "${NIXPKGS_INPUT:-}" ]; then
    nix_args="--override-input nixpkgs ${NIXPKGS_INPUT}"
  fi
  NIX_CONFIG="extra-substituters=https://cache.numtide.com https://cache.nixos.org extra-trusted-public-keys=niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g= cache.nixos.org-1:6NCHd0Y9XMDA9/4lQpJzN3fPXMmHIvWtGBJpvGm0w1g=" \
    nix run github:nix-community/home-manager/release-26.05 -- \
          switch --accept-flake-config --flake ".#${username}@${nix_arch}" ${nix_args}
)
