#!/usr/bin/env zsh

os=$(uname -s)

echo install: user
cp zprofile $HOME/.zprofile
cp zshrc $HOME/.zshrc
cp zshenv $HOME/.zshenv
rm -rf ~/.zsh.d
mkdir $HOME/.zsh.d
( cd zsh.d; tar cf - . ) | ( cd $HOME/.zsh.d; tar xf - )
( cd d; tar cf - . ) | ( cd $HOME; tar xf - )
chmod 755 $HOME
mkdir -p $HOME/go
