# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "raring64-vanilla"
  config.vm.hostname = "base.local.raines.me"
  config.vm.network :private_network, ip: "192.168.56.9"
  config.ssh.forward_agent = true
  config.cache.auto_detect = true
  # config.vm.synced_folder "#{ENV['HOME']}/src/elasticsearch/target/releases", "/etc/puppet/files"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1000"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision :shell, :path => "bin/bootstrap", :args => "raring"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "#{ENV['HOME']}/src/hula/puppet/manifests"
    puppet.module_path    = "#{ENV['HOME']}/src/hula/puppet/modules"
    puppet.manifest_file  = "vagrant.pp"
    puppet.options = ["--node_terminus=exec",
                      "--external_nodes=/usr/local/bin/nodes"]
  end
end
