# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "raring64"
  config.vm.hostname = "base"
  config.vm.network :private_network, ip: "192.168.56.9"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end


  # group { "puppet":
  #   ensure => "present",
  # }
  #
  # File { owner => 0, group => 0, mode => 0644 }
  #
  # file { '/etc/motd':
  #   content => "Welcome to your Vagrant-built virtual machine!
  #               Managed by Puppet.\n"
  # }
  
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
  end
end
