# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  boxes = {:es1 => "192.168.56.10",
           :es2 => "192.168.56.20",
           :es3 => "192.168.56.30"}

  #boxes = {:es1 => "192.168.56.10"}

  boxes.each do |n, ip|
    config.vm.define n do |box|
      box.vm.box = "raring64"
      box.vm.hostname = n.to_s
      box.vm.network :private_network, ip: ip
      box.vm.synced_folder "#{ENV['HOME']}/src/elasticsearch/target/releases", "/etc/puppet/files"
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end
  end

  # config.vm.provision :shell, :path => "bootstrap", :args => "raring"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../puppet/manifests"
    puppet.module_path    = "../puppet/modules"
    puppet.manifest_file  = "site.pp"
    puppet.facter = {
      "fqdn" => "bootstrap",
      "options" => "--fileserverconfig=/vagrant/fileserver.conf"
    }
  end

end
